# Archivos para dashboard

In [2]:
#Carga de datos
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

cols = ['time_idx', 'date', 'store_nbr', 'item_nbr', 'city', 'state',
        'type', 'cluster', 'family', 'class', 'perishable']
panel = pd.read_parquet('/content/drive/MyDrive/TFM/favorita_panel_corregido.parquet', columns=cols)
panel = panel.rename(columns={'type': 'store_type'})
print(panel.shape)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
(4804366, 11)

In [4]:
#Crear archivo de fechas
fechas = panel[['time_idx', 'date']].drop_duplicates().sort_values('time_idx').reset_index(drop=True)
fechas.to_csv('/content/drive/MyDrive/TFM/time_idx_fechas.csv', index=False)
print('fechas:', fechas.shape)
fechas.head()

fechas: (1687, 2)

   time_idx       date
0         0 2013-01-02
1         1 2013-01-03
2         2 2013-01-04
3         3 2013-01-05
4         4 2013-01-06

In [5]:
#Crear archivo de metadatos
metadata = panel[['store_nbr', 'item_nbr', 'city', 'state', 'store_type',
                   'cluster', 'family', 'class', 'perishable']].drop_duplicates().reset_index(drop=True)
metadata.to_csv('/content/drive/MyDrive/TFM/metadata_series.csv', index=False)
print('metadata_series:', metadata.shape, '(esperado cercano a 3.981 series retenidas)')
metadata.head()

metadata_series: (3981, 9) (esperado cercano a 3.981 series retenidas)

,store_nbr,item_nbr,city,state,store_type,cluster,family,class,perishable
0,1,122095,Quito,Pichincha,D,13,DAIRY,2124,1
1,1,123347,Quito,Pichincha,D,13,DAIRY,2114,1
2,1,129635,Quito,Pichincha,D,13,DAIRY,2112,1
3,1,158842,Quito,Pichincha,D,13,DAIRY,2124,1
4,1,164088,Quito,Pichincha,D,13,DAIRY,2116,1